#!/bin/bash
mkdir -p ~/.config/ranger
mkdir -p ~/.config/fontconfig
mkdir -p ~/.config/dunst

stow bash -t ~
stow emacs -t ~
stow i3 -t ~/.config/i3
stow ranger -t ~/.config/ranger
stow vim -t ~
stow x -t ~
stow scripts -t ~
stow fontconfig -t ~/.config/fontconfig
stow dunst -t ~/.config/dunst
