#!/bin/bash

sudo pacman -S xorg \
       stow \
       vim \
       emacs \
       git \
       ranger \
       dunst \
       newsboat \
       lxappearance \
       arandr \
       sxiv \
       feh \
       firefox \
       compton 
