#!/bin/bash
mkdir -p ~/.config/ranger
mkdir -p ~/.config/fontconfig
mkdir -p ~/.config/dunst
mkdir -p ~/.config/i3

stow bash -t ~
stow dunst -t ~/.config/dunst
stow emacs -t ~
stow fontconfig -t ~/.config/fontconfig
stow i3 -t ~/.config/i3
stow ranger -t ~/.config/ranger
stow scripts -t ~
stow vim -t ~
stow x -t ~
