#!/bin/bash
choices="$(ls ~/.screenlayout/)\nother"
chosen=$(echo -e "$choices" | dmenu -i -p "Display:")

[ "$chosen" != "" ] || exit

if [ "$chosen" == "other" ]; then
	arandr
else
	~/.screenlayout/$chosen
fi
