#!/bin/sh

while true; do
	battery=""
	capacity=$(cat /sys/class/power_supply/BAT0/capacity)
	if [ $capacity -le 90 ]; then
		battery+=""
	elif [ $capacity -le 30 ]; then
		battery+=""
	elif [ $capacity -le 10 ]; then
		battery+=""
	else
		battery+=""
	fi
	battery+="BAT $capacity%"
	# Volume
	volume=""
	mute="$(pactl list sinks | grep "Mute" | awk '{print $2}')"
	if [ "$mute" = "yes" ]; then
		volume+=""
	else
		volume+=""
	fi
	volume+="VOL $(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')"
	xsetroot -name " $volume%  | $battery  | TIME $(date +" %b %d (%a) %R")"
	sleep 30
done
