#!/bin/sh

while true; do
	battery=""
	capacity=$(cat /sys/class/power_supply/BAT0/capacity)
	if [$capacity -le 90]; then
		battery+=""
	elif [$capacity -le 30]; then
		battery+=""
	elif [$capacity -le 10]; then
		battery+=""
	else
		battery+=""
	fi
	battery+="BAT $capacity%"
	xsetroot -name " $battery  | TIME $(date +" %b %d (%a) %R")"
	sleep 5
done
