#!/bin/sh
# Write/remove a task to do later.

FILE=$HOME/.todo
PROMPT="Add/delete a task"

ACTION="cat $FILE | dmenu -l 10 -p '$PROMPT:' "
CMD=$(eval $ACTION)
while [ -n "$CMD" ]; do
	grep -q "^$CMD" $FILE
	if [ $? = 0 ]; then
		grep -v "^$CMD" $FILE > /tmp/todo
		mv /tmp/todo $FILE
        HEIGHT=$(($HEIGHT-1))
        ACTION="cat $FILE | dmenu -l 10 -p '$PROMPT:' "
	else
		echo "$CMD" >> $FILE
        HEIGHT=$(($HEIGHT+1))
        ACTION="cat $FILE | dmenu -l 10 -p '$PROMPT:' "
	fi
	
	CMD=$(eval $ACTION)

done
exit 0
