[ -f ~/.bashrc ] && source "$HOME/.bashrc"
export EDITOR="vim"
export TERMINAL="st"
export BROWSER="firefox"
export PATH="$PATH:$HOME/.scripts"
export QT_QPA_PLATFORMTHEME="qt5ct"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
